spring:
  application:
    name: userhub
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userhub
    username: root
    password: "test"
server:
  port: 8080